[package]
name = "sourcepp"
version = "0.0.0"
edition = "2024"
include = [
    "/src",
    "/include",
    "build.rs",
    "readme.md",
    "/vendored",
    "!.git",

    # these test files are way too big
    "!/vendored/cryptopp/TestVectors",
    "!/vendored/cryptopp/TestScripts",
    "!/miniz/tests",
    "!/minizip-ng/test",
    "!/webp/webp_js",
    "!/webp/tests"
]

[build-dependencies]
cmake = "0.1.54"
cxx-build = "1.0.190"

[features]
bsppp = []#["vpkpp"]
dmxpp = []
fspp = []#["bsppp", "kvpp", "steampp", "vpkpp"]
gamepp = []
kvpp = []
mdlpp = []
sndpp = []
steampp = []#["kvpp"]
toolpp = []#["kvpp"]
vcryptpp = []
vpkpp = []#["kvpp"]
vtfpp = []

[dependencies]
cxx = { version = "1.0.190", features = ["c++20"] }
