[package]
name = "sourcepp-sys"
version = "0.0.0"
edition = "2024"
links = "sourcepp"

[build-dependencies]
bindgen = "0.72.1"
cmake = "0.1.54"
regex = { version = "1.12.2", default-features = false }

[features]
bsppp = []#["vpkpp"]
dmxpp = []
fspp = []#["bsppp", "kvpp", "steampp", "vpkpp"]
gamepp = []
kvpp = []
mdlpp = []
sndpp = []
steampp = []#["kvpp"]
toolpp = []#["kvpp"]
vcryptpp = []
vpkpp = []#["kvpp"]
vtfpp = []