[package]
name = "sourcepp-sys"
version = "0.0.0"
edition = "2024"
links = "sourcepp"
include = [
    "/src",
    "build.rs",
    "readme.md",
    "/vendored",
    "!.git",

    # these test files are way too big
    "!/vendored/cryptopp/TestVectors",
    "!/vendored/cryptopp/TestScripts",
    "!/miniz/tests",
    "!/minizip-ng/test",
    "!/webp/webp_js",
    "!/webp/tests"
]

[build-dependencies]
bindgen = "0.72.1"
cmake = "0.1.54"
regex = { version = "1.12.2", default-features = false }

[features]
bsppp = []#["vpkpp"]
dmxpp = []
fspp = []#["bsppp", "kvpp", "steampp", "vpkpp"]
gamepp = []
kvpp = []
mdlpp = []
sndpp = []
steampp = []#["kvpp"]
toolpp = []#["kvpp"]
vcryptpp = []
vpkpp = []#["kvpp"]
vtfpp = []